version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/team-Omo-BE
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before_deploy.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_deploy.sh
      timeout: 300
      runas: ubuntu
