version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Omo-Web-Server
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before_deploy_first.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_deploy_first.sh
      timeout: 120
      runas: ubuntu
  BeforeInstall:
    - location: scripts/before_deploy_second.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_deploy_second.sh
      timeout: 120
      runas: ubuntu
