version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Omo-Web-Server
    overwrite: yes
    filter: ["/Omo-Web-Server/*"]

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before_deploy_first.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_deploy_first.sh
      timeout: 120
      runas: ubuntu
